apiVersion: core.hydra.io/v1alpha1
kind: ComponentSchematic
metadata:
  name: fireworks-worker
  version: "1.0.0"
  description: Fireworks Worker Container
spec:
  workloadType: core.hydra.io/v1.Replicated
  parameters:
  - name: objecttype
    description: The color of the fireworks
    type: string
  ostype: linux
  containers:
    - name: worker
      ports:
        - 80
      env:
      - name: OBJECT_TYPE
        fromParam: objecttype
      image:
        name: vipulmmsft/azure-mesh-fireworks-worker-v1:0.4-strech
        digest: sha256:6c3c624b58dbbcd3c0dd82b4c53f04194d1247c6eebdaab7c610cf7d66709b3b
