apiVersion: core.hydra.io/v1alpha1
kind: ComponentSchematic
metadata:
  name: fireworks-worker
  version: 1.0.0
  description: Fireworks Worker Container
spec:
  workloadType: core.hydra.io/v1.Replicated
  parameters:
  - name: firework_color
    description: The color of the firework
    type: string
  - name: object_counter_address
    description: The address of the web frontend
    type: string
  ostype: linux
  containers:
    - name: worker
      ports:
      - name: http
        containerPort: 80
      resources:
        cpu: 
          required: 2.0
        memory: 
          required: 4G      
      env:
      - name: OBJECT_TYPE
        fromParam: firework_color
      - name: OBJECTCOUNTER_ADDRESS
        fromParam: object_counter_address
      image: vipulmmsft/azure-mesh-fireworks-worker-v1:0.4-strech
