apiVersion: core.hydra.io/v1alpha1
kind: OperationalConfiguration
metadata:
    name: fireworks-deployment-config
    description: Customized version of the fireworks components
spec:
  variables:
    - name: objectcounter
      value: 500
    - name: objectcounteraddress
      value: fireworks-frontend.testNetworkScope2
    - name: color1
      value: red
    - name: color2 
      value: green
    - name: color3 
      value: blue
    - name: web-count
      value: 1
    - name: worker-count
      value: 1
    - name: subnet_name_value 
      value: /subscriptions/13ad2c84-84fa-4798-ad71-e70c07af873f/resourceGroups/suhuruli-fireworks/providers/Microsoft.Network/virtualNetworks/suhuruli-vnet/subnets/hydra
  scopes: 
    - name: testNetworkScope2
      type: core.hydra.io/v1alpha1.Network
      properties:
        - name: networkName
          value: "[fromVariable(subnet_name_value)]"
  components:
    - componentName: fireworks-frontend
      instanceName: fireworks-frontend
      parameterValues: 
        - name: objectcounter
          value: "[fromVariable(objectcounter)]"
      traits:
        - type: core.hydra.io/v1alpha1.ManualScaler
          properties:
            replicaCount: "[fromVariable(web-count)]"
      applicationScopes: 
        - name: testNetworkScope2
          type: core.hydra.io/v1alpha1.Network
    - componentName: fireworks-worker
      instanceName: fireworks-worker1
      parameterValues: 
        - name: firework_color
          value: "[fromVariable(color1)]"
        - name: object_counter_address
          value: "[fromVariable(objectcounteraddress)]"
      traits:
        - type: core.hydra.io/v1alpha1.ManualScaler
          properties:
            replicaCount: "[fromVariable(worker-count)]"     
      applicationScopes: 
        - name: testNetworkScope2
          type: core.hydra.io/v1alpha1.Network  