apiVersion: core.hydra.io/v1alpha1
kind: OperationalConfiguration
metadata:
    name: fireworks-deployment-config
    description: Customized version of the fireworks components
spec:
  variables:
    - name: web-port
      value: 80
    - name: objectcounter
      value: 500
    - name: color1
      value: red
    - name: color2 
      value: green
    - name: color3 
      value: blue
    - name: web-count
      value: 1
    - name: worker-count
      value: 1
    - name: network_name_value 
      value: fireworks-subnet
    - name: subnet_prefix_value
      value: 172.16.0.1/24
  scopes: 
    - name: fireworks-vnet
      type: core.hydra.io/v1alpha1.Network
      properties:
        - name: networkName
          value: "[fromVariable(network_name_value)]"
        - name: subnetPrefix          
          value: "[fromVariable(subnet_prefix_value)]"
  components:
    - componentName: fireworks-frontend
      instanceName: fireworks-frontend
      parameterValues: 
        - name: objectcounter
          value: "[fromVariable(objectcounter)]"
      traits:
        - name: web-scaler
          type: core.hydra.io/v1alpha1.ManualScaler
          properties:
            replicaCount: "[fromVariable(web-count)]"
        - name: fireworks-ingress
          type: core.hydra.io/v1alpha1.Ingress
          public: true
          parameterValues:
            - name: port
              value: "[fromVariable(web-port)]"
      applicationScopes: 
        - name: fireworks-vnet
          type: core.hydra.io/v1alpha1.Network

    - componentName: fireworks-worker
      instanceName: fireworks-worker1
      parameterValues: 
            - name: firework_color
              value: "[fromVariable(color1)]"
      traits:
        - name: worker-scaler
          type: core.hydra.io/v1alpha1.ManualScaler
          properties:
            replicaCount: "[fromVariable(worker-count)]"     
      applicationScopes: 
        - name: fireworks-vnet
          type: core.hydra.io/v1alpha1.Network  

    - componentName: fireworks-worker
      instanceName: fireworks-worker2
      parameterValues: 
            - name: firework_color
              value: "[fromVariable(color2)]"
      traits:
        - name: worker-scaler
          type: core.hydra.io/v1alpha1.ManualScaler
          properties:
            replicaCount: "[fromVariable(worker-count)]"
      applicationScopes: 
        - name: fireworks-vnet
          type: core.hydra.io/v1alpha1.Network

    - componentName: fireworks-worker
      instanceName: fireworks-worker3   
      parameterValues: 
            - name: firework_color
              value: "[fromVariable(color3)]"       
      traits:
        - name: worker-scaler
          type: core.hydra.io/v1alpha1.ManualScaler
          properties:
            replicaCount: "[fromVariable(worker-count)]"
      applicationScopes: 
        - name: fireworks-vnet
          type: core.hydra.io/v1alpha1.Network