apiVersion: core.hydra.io/v1alpha1
kind: OperationalConfiguration
metadata:
    name: fireworks-deployment-config
    description: Customized version of the fireworks components
spec:
  variables:
    - name: web-port
      value: 8080
    - name: urls 
      value: "http://+:8080"
    - name: objectcounter
      value: "1"
    - name: color1
      value: "red"
    - name: color2 
      value: "green"
    - name: color3 
      value: "blue"
    - name: web-count
      value: 1
    - name: worker-count
      value: 1
    - name: network_name_value 
      value: ""
    - name: subnetPrefix
      value: ""
  scopes: 
    - name: fireworks-vnet
      type: core.hydra.io/v1alpha1.Network
      properties:
        - name: networkName
          value: "[fromVariable(network_name_value)]"
        - name: subnetPrefix          
          value: "[fromVariable(subnet_prefix_value)]"
  components:
    - componentName: fireworks-frontend
      instanceName: fireworks-frontend
      parameterValues: 
        - name: urls 
          value: "[fromVariable(urls)]"
        - name: objectcounter
          value: "[fromVariable(objectcounter)]"
      traits:
        - name: web-scaler
          type: core.hydra.io/v1alpha1.ManualScaler
          properties:
            replicaCount: "[fromVariable(web-count)]"
        - name: fireworks-ingress
          type: core.hydra.io/v1alpha1.Ingress
          public: true
          parameterValues:
            - name: port
              value: "[fromVariable(web-port)]"
      applicationScopes: 
        - name: fireworks-vnet
          type: core.hydra.io/v1alpha1.Network
    - componentName: fireworks-worker
      instanceName: fireworks-worker1
      parameterValues: 
            - name: objecttype
              value: "[fromVariable(color1)]"
      traits:
        - name: worker-scaler
          type: core.hydra.io/v1alpha1.ManualScaler
          properties:
            replicaCount: "[fromVariable(worker-count)]"     
      applicationScopes: 
        - name: fireworks-vnet
          type: core.hydra.io/v1alpha1.Network     
    - componentName: fireworks-worker
      instanceName: fireworks-worker2
      parameterValues: 
            - name: objecttype
              value: "[fromVariable(color2)]"
      traits:
        - name: worker-scaler
          type: core.hydra.io/v1alpha1.ManualScaler
          properties:
            replicaCount: "[fromVariable(worker-count)]"
      applicationScopes: 
        - name: fireworks-vnet
          type: core.hydra.io/v1alpha1.Network
    - componentName: fireworks-worker
      instanceName: fireworks-worker3   
      parameterValues: 
            - name: objecttype
              value: "[fromVariable(color3)]"       
      traits:
        - name: worker-scaler
          type: core.hydra.io/v1alpha1.ManualScaler
          properties:
            replicaCount: "[fromVariable(worker-count)]"
      applicationScopes: 
        - name: fireworks-vnet
          type: core.hydra.io/v1alpha1.Network